### ISSUE TITLE
How to select a node page - Suggested text fixes

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldfoundation/info_gridmanual#110]
https://sdk.threefold.io/#/explore_nodes

- [x] One of the first ~~thing~~ things to do
- [x] To which farm this ~~nodes~~ node belongs to.
- [x] Specify ~~is~~ if this node capacity can be reserved with FreeTFT or not.
- [x] to take ~~in~~ into account
- [x] must ~~be~~ all be free to use or not
- [x] ~~an~~ a heartbeat
- [x] We consider a node offline ~~is~~ if the explorer did not ~~received~~ receive a heartbeat for more than 10 minutes.
- [x] Make sure to always skip offline ~~node~~ nodes when doing a reservation. Falling to do so will ~~let~~ leave your reservation blocked until ~~it’s~~ its provision timeout is reached and then cancelled.

**Comment by zaibon** [comment]
Can you please create a PR with all your proposed change, like this is it quite hard to process. PR are more easy to review and comment. thanks
