### ISSUE TITLE
Windows docker setup steps do not match latest docker for windows version

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldfoundation/info_gridmanual#134]
https://sdk.threefold.io/#/3sdk_windows

Guide tells me to go to a menu option that doesn't exist ( Shared drives ) When attempting to follow the picture instead I get in the correct menu but there is no C drive available there.

What is actually required is to go to Resources, File Sharing, click the plus, and select the C drive under this computer. Then apply and restart.

![image](https://user-images.githubusercontent.com/59569757/88156417-ae580f00-cc09-11ea-8f09-7161a5b91e71.png)

**Comment by xmonader** [comment]
not using docker anymore
