### ISSUE TITLE
3botconnect should be a linked with setup guide under sdk_install

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldfoundation/info_gridmanual#136]
https://sdk.threefold.io/#/3sdk_install

I was linked here from the threefold capacity site how to become a farmer.

When following these steps and requirements there is no mention of having to install 3botconnect or writing down seed phrases. However when going through all the requirements ( Install docker and set it up, download and run the SDK ... )

I was never required in the process to install the 3botconnect app or write down a seed phrase.
Suddenly in the 3bot use flow there is a reference to starting your 3bot connect app.

This should be in the 3SDK requirements and correctly link the user to the setup guides, rather than having them figure out where the info is on their own.

**Comment by rkhamis** [comment]
docs now first ask to have 3botconnect
