### ISSUE TITLE
When following the farm setup, the user never gets to a working localhost:4000

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldfoundation/info_gridmanual#137]
https://sdk.threefold.io/#/v2_jsx_farmsetup?id=prerequisite-install-3sdk

Which links to 

https://sdk.threefold.io/#/3sdk_install

This has the requirements
Docker
Chrome browser for OSX users

I have installed both these and downloaded and ran the SDK successfully

However now it tells me to go to https://sdk.threefold.io/#/3sdk_use , this is just a listing of possible available commands and not a guide on what commands to actually execute to be able to browse to localhost:4000 and continue with the farm setup. This was blocking in being able to set up my own farm.

**Comment by rkhamis** [comment]
this is outdated, no? better check on new farming docs
