### ISSUE TITLE
2 dns names

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_gridmanual#145]
manual.threefold.io (will be link): development/master
backwards sdk... stays working

old sdk -> master_jsx branch -> sdk.threefold.io  

sdk 2.1 -> master -> manual.threefold.io 
sdk 2.1 staging —> manual2.threefold.io

**Comment by despiegk** [comment]
testnet:
- manual_testnet.threefold.io (branch: on this repo: development_testnet)

**Comment by xmonader** [comment]
old sdk -> master_jsx branch -> sdk.threefold.io
sdk 2.1 -> master -> manual.threefold.io
sdk 2.1 -> development -> manual2.threefold.io ?
