### ISSUE TITLE
marketplace - move home page marketplace

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_gridmanual#147]
![image](https://user-images.githubusercontent.com/6021844/89503947-94046080-d7c7-11ea-9db8-7170f7a75883.png)
needs to be put on this repo, so we can make info_threefold private for now

**Comment by sasha-astiadi** [comment]
migrated to https://github.com/threefoldtech/js-sdk/blob/development/jumpscale/packages/marketplace/frontend/components/Home.vue
