### ISSUE TITLE
manual 2.1  - v2_jsx_farmsetup

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_gridmanual#155]
http://localhost:3000/manual#/v2_jsx_farmsetup

seems to be very outdated
also there should be no links to docs on github somwhere

talks about 3sdk still

**Comment by gmachtel** [comment]
I have a farm_setup.md made now, should be more generic and no longer referring to the way that 3bot was set up (local/marketplace, through 3sdk/js-sdk as all left out, described elsewhere).
