### ISSUE TITLE
manual 2.1 - add text to ssh connect

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/info_gridmanual#166]
https://manual2.threefold.io/#/ssh_connect

**Comment by sasha-astiadi** [comment]
even only a little, so i know what its about, and i will review and edit later

**Comment by xmonader** [comment]
![image](https://user-images.githubusercontent.com/64129/90015432-e56d8d80-dca8-11ea-860a-c3024d24fecb.png)
It's only `ssh username@containerip` instructions are given in the end of ever successful deployment
