### ISSUE TITLE
manual 2.1 - add content to develop.md

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/info_gridmanual#167]

**Comment by sasha-astiadi** [comment]
just add some texts about what the chatflow is, i will edit and make it more detailed

**Comment by xmonader** [comment]
https://github.com/threefoldfoundation/info_gridmanual/commit/15dface6b0e2dd3c7cbdeb19eb722ed35c9fc037 and chatflows exist here https://manual2.threefold.io/#/develop_chatflow
