### ISSUE TITLE
manual 2.1 - add intro to jumpscale: internals.md

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/info_gridmanual#169]
https://manual2.threefold.io/#/internals

**Comment by sasha-astiadi** [comment]
just add some texts about what the chatflow is, i will edit and make it more detailed

**Comment by xmonader** [comment]
@sasha-astiadi content for chatflows already there in develop/chatflows https://manual2.threefold.io/#/develop_chatflow

**Comment by sasha-astiadi** [comment]
done
