### ISSUE TITLE
Manual says executable is called "3Bot" actually still called "threebot"

### ISSUE THREAD

**Issue by scottyeager** [threefoldfoundation/info_gridmanual#192]
The manual page to create a local 3Bot has been updated to indicate the executable is `3Bot` but the installed executable is still `threebot`.

https://manual2.threefold.io/#/local_3bot

**Comment by xmonader** [comment]
definitely caused by a global search and replace

**Comment by xmonader** [comment]
closed via ffb3baa0834394e5fd0ce678cecfedbbb51621e4
