### ISSUE TITLE
what is Hercules chatflow?

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/info_gridmanual#194]
https://manual2.threefold.io/#/chatflow_hercule ? looks like it's just minio?

**Comment by despiegk** [comment]
just remove from menu

**Comment by muhamadazmy** [comment]
- Yes, Hecrules is just a fully working minio solution. 
- I can see that the documentation is already out of date, (pre pool era)

Do we need to update it for this release? since I can see already this link is not reachable from the navigation tree.
