### ISSUE TITLE
Update capacity pool docs to include js-ng [development_capacitypool]

### ISSUE THREAD

**Issue by ranatrk** [threefoldfoundation/info_gridmanual#197]
## Phase 2 (After capacity reservation)
- [ ] Getting Started
  - [ ] Deploy your first solution (chatflows part)
  - [ ] Tutorials
- [ ] Admin Panel
  - [ ] Chatflows
- [ ] Develop
  - [ ] Provisioning code
  - [ ] Solutions

**Comment by rkhamis** [comment]
all addressed
