### ISSUE TITLE
GCC is a requirement for local Threebot

### ISSUE THREAD

**Issue by scottyeager** [threefoldfoundation/info_gridmanual#199]
The manual page linked below should include `gcc` as a dependency for local Threebot installation, as it's needed to build `crc16` as a dependency.

https://manual.threefold.io/#/getting_started_3bot

**Comment by waleedhammam** [comment]
Thank you so much @scottyeager for the testing also for getting to a lot of installation scenarios.

I've tried it already on a fresh docker container with Ubuntu 20 but it's working fine without any problems

Here's the installation logs: https://gist.github.com/waleedhammam/aeee3ced91ec2a022b39590b56d5d2d9

**Comment by scottyeager** [comment]
Sure thing, @waleedhammam.

I see what's happening here. Pip depends on gcc via build essentials on Ubuntu, but this is not the case on Arch. This came up while trying to run Threebot in a fresh Arch container to see if I can isolate the issue I'm still having on my local Arch system.

Since Ubuntu is what's officially supported right now, I'd be happy to stick with my working Ubuntu container as to not distract you all too much :smile:
