### ISSUE TITLE
Add cookie consent banner to sdk.threefold.io

### ISSUE THREAD

**Issue by Sacha96** [threefoldfoundation/info_gridmanual#218]
<script type="text/javascript" src="//www.freeprivacypolicy.com/public/cookie-consent/3.1.0/cookie-consent.js"></script>
<script type="text/javascript">
document.addEventListener('DOMContentLoaded', function () {
cookieconsent.run({"notice_banner_type":"headline","consent_type":"express","palette":"light","language":"en","website_name":"https://sdk.threefold.io/#/","cookies_policy_url":"https://wiki.threefold.io/#/privacypolicy"});
});
</script>

<script type="text/plain" cookie-consent="functionality">window.$crisp=[];window.CRISP_WEBSITE_ID="1a5a5241-91cb-4a41-8323-5ba5ec574da0";(function(){d=document;s=d.createElement("script");s.src="https://client.crisp.chat/l.js";s.async=1;d.getElementsByTagName("head")[0].appendChild(s);})();</script>

<script type="text/plain" cookie-consent="tracking" async src="https://www.googletagmanager.com/gtag/js?id=UA-100065546-6"></script>
<script type="text/plain" cookie-consent="tracking">
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-100065546-6');
</script>

<noscript>Cookie Consent by <a href="https://www.FreePrivacyPolicy.com/free-cookie-consent/" rel="nofollow noopener">FreePrivacyPolicy.com</a></noscript>

**Comment by ehab-hassan** [comment]
done at 
https://sdk.threefold.io/#/

**Comment by xmonader** [comment]
![image](https://user-images.githubusercontent.com/64129/92223309-929a8680-eea0-11ea-943b-ec232e41c7cf.png)
