### ISSUE TITLE
3Bot admin - collaborate in writing about 3bot wallet

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/info_gridmanual#223]
collaborate on the create and import. and wallet details chatflow on 3bot_wallet.md

[wiki section](https://manual2.threefold.io/#/3bot_wallet)

file location: [3bot_wallet](https://github.com/threefoldfoundation/info_gridmanual/blob/development/src/3bot_sysadmin/admin_tools/3bot_wallet.md)

**Comment by xmonader** [comment]
7006e47ae51b285518c37c05e0be3f3b51e3caf1
