### ISSUE TITLE
write the 3bot farm management section of the manual

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/info_gridmanual#231]
write the 3bot farm management section of the manual
https://manual2.threefold.io/#/3bot_farm_mgmt

make sure its linked to the farm setup section somehow
https://manual2.threefold.io/#/farm_setup_management

**Comment by sasha-astiadi** [comment]
#

**Comment by zaibon** [comment]
https://github.com/threefoldfoundation/info_gridmanual/commit/d7adae7908e43413ee9c19fae82bed48edf9af89
