### ISSUE TITLE
"Set up a Solar Wallet (Testnet)" explains how to set up a trustline and receive FreeTFT

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/info_gridmanual#243]
It should explain how to set up a Testnet TFT trustline

**Comment by sasha-astiadi** [comment]
at the moment solar is not a good wallet to list on since me and @xmonader  tried to add tft as asset and faced error.

**Comment by robvanmieghem** [comment]
I had no ptoblem adding it but there indeed seem to be some issues in the latest release

**Comment by robvanmieghem** [comment]
But I see setting up the Solar wallet has been removed from the manual so I guess this issue can be closed
