### ISSUE TITLE
put sizing params on images

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_gridmanual#245]
e.g.in https://wiki.threefold.io/#/farming_diy_guide

walk over manual and the images which are clearly out of size put sizing params in, try to do it in such a way that the text on the image is +- same size as text on the wiki page itself

example

![image](https://user-images.githubusercontent.com/6021844/93011712-decc8180-f598-11ea-91dd-07405145e329.png)

but there are quite some like this

**Comment by PeterNashaat** [comment]
- I've checked every image in our wikis, grid manual, website and blog.
- put params to every out of size image.
- push my changes to development branch,  all will be fixed next merge to production
