### ISSUE TITLE
Review Smart contract for IT scripts

### ISSUE THREAD

**Issue by OmarElawady** [threefoldfoundation/info_gridmanual#267]
Some of the scripts contain outdated code.

Todo:

- [ ] 0-Containers
- [ ] Overlay network
- [ ] Web Gateway
- [ ] Kubernetes
- [ ] 0-DB storage
- [ ] Virtual disk

**Comment by OmarElawady** [comment]
More fixes in: #269

**Comment by xmonader** [comment]
merged
