### ISSUE TITLE
Look at the farming pages and see if the description of getting a farm_id and more is cleary documented enough -->

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldfoundation/info_gridmanual#63]
https://github.com/threefoldfoundation/info_tfgridsdk/blob/d4881acffdda7e0c3d6e80d8dd55cac7ba838dfc/src/gettingstarted/online_resources.md#L8-L8

**Comment by despiegk** [comment]
still relevant?

**Comment by zaibon** [comment]
@weynandkuijpers can you update this issue please, your link is dead. Is this still relevant ?
