### ISSUE TITLE
some links are not working in SDK in installation docs

### ISSUE THREAD

**Issue by Pishoy** [threefoldfoundation/info_gridmanual#96]
when access https://sdk3.threefold.io/#/3sdk_install

- some issue in `Install 3sdk` topic as below 
![image](https://user-images.githubusercontent.com/21987477/81299195-20db3900-9076-11ea-9e8a-4b0227f39fb3.png)

- issue in clicking on `Troubleshooting`
![image](https://user-images.githubusercontent.com/21987477/81299074-f7221200-9075-11ea-8cc5-45fc81e19775.png)

- please make sure that those topics are exist and working properly in wikis 
https://github.com/threefoldtech/jumpscaleX_core/tree/development/docs/3sdk

**Comment by achimha** [comment]
A lot of people have Mac and most use Chrome. There should be a hint about the certificate problem for https on the nonstandard port to save some troubleshooting time.

**Comment by rkhamis** [comment]
the manual has been updated
