### ISSUE TITLE
Example code reference outdated path

### ISSUE THREAD

**Issue by zaibon** [threefoldfoundation/info_gridmanual#98]
followup from https://github.com/threefoldtech/home/issues/688

Let's please go over all the example code and make sure they are all up to date.

**Comment by weynandkuijpers** [comment]
Stepped through some of the examples.  changes are needed.  I Will start with the ones listed in the SDK manuals and then. (where not based on includes go to the repo ones.

**Comment by sasha-astiadi** [comment]
@zaibon @weynandkuijpers is this resolved? please confirm / close or ill transfer this issue to the latest project
